import express from "express";
import fs from "fs";
import path from "path";

const appScript = express();
const appVoice = express();
const appVideo = express();
const appSubtitle = express();

const PORT_SCRIPT = 8000;
const PORT_VOICE = 8001;
const PORT_VIDEO = 8002;
const PORT_SUBTITLE = 8003;

// Ensure storage dirs exist
const STORAGE_ROOT = path.resolve(process.cwd(), "../storage");
if (!fs.existsSync(STORAGE_ROOT)) fs.mkdirSync(STORAGE_ROOT);

["audio", "video", "subtitles"].forEach(dir => {
    const p = path.join(STORAGE_ROOT, dir);
    if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true });
});

// --- Script AI ---
appScript.use(express.json());
appScript.post("/generate-script", (req, res) => {
    console.log("📝 [Script AI] Generating script for:", req.body.topic);
    res.json({
        success: true,
        script: "This is a mock script generated by the test server. #Motivation #Grind"
    });
});
appScript.listen(PORT_SCRIPT, () => console.log(`🤖 Script AI running on ${PORT_SCRIPT}`));

// --- Voice AI ---
appVoice.use(express.json());
appVoice.post("/generate-voice", (req, res) => {
    console.log("🗣️ [Voice AI] Generating voice...");
    const filePath = "storage/audio/mock_voice.mp3";
    const absPath = path.join(process.cwd(), "..", filePath);
    fs.writeFileSync(absPath, "mock audio content");
    res.json({
        success: true,
        audio_path: filePath
    });
});
appVoice.listen(PORT_VOICE, () => console.log(`🤖 Voice AI running on ${PORT_VOICE}`));

// --- Subtitle AI ---
appSubtitle.use(express.json());
appSubtitle.post("/generate-subtitles", (req, res) => {
    console.log("📝 [Subtitle AI] Generating subtitles...");
    const filePath = "storage/subtitles/mock_subs.srt";
    const absPath = path.join(process.cwd(), "..", filePath);
    fs.writeFileSync(absPath, "1\n00:00:01,000 --> 00:00:05,000\nMock subtitle");
    res.json({
        success: true,
        subtitle_path: filePath
    });
});
appSubtitle.listen(PORT_SUBTITLE, () => console.log(`🤖 Subtitle AI running on ${PORT_SUBTITLE}`));

// --- Video AI ---
appVideo.use(express.json());
appVideo.post("/generate-video", (req, res) => {
    console.log("🎬 [Video AI] Generating video...");
    const filePath = "storage/video/mock_video.mp4";
    const absPath = path.join(process.cwd(), "..", filePath);
    fs.writeFileSync(absPath, "mock video content");
    res.json({
        success: true,
        video_path: filePath
    });
});
appVideo.listen(PORT_VIDEO, () => console.log(`🤖 Video AI running on ${PORT_VIDEO}`));
